CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR (50) NOT NULL, password VARCHAR (50) NOT NULL, created_at TIMESTAMP);
CREATE TABLE post (id SERIAL PRIMARY KEY, text TEXT NOT NULL, created_at TIMESTAMP, user_id VARCHAR(50) NOT NULL);
CREATE TABLE comment (id SERIAL PRIMARY KEY,text TEXT, post_id VARCHAR (50) NOT NULL, user_id VARCHAR (50) NOT NULL, created_at TIMESTAMP);
CREATE TABLE likes (id SERIAL PRIMARY KEY, user_id VARCHAR (50) NOT NULL, post_id VARCHAR(50), comment_id VARCHAR(50));